### ISSUE TITLE
Seems support is dropped for Windows BTS 1.0.2

### ISSUE THREAD

**Issue by Beanow** [katana-dev/docs#6]
@skconrad wrote
> Get it while you can
BTS for Katana (WIN) (1.0.2)
https://static.roland.com/assets/media/zip/bts_katana_w102.zip
>
> https://web.archive.org/web/20170427195914/https://www.boss.info/latinamerica/support/by_product/katana-100/updates_drivers/0143296a-ed7b-4530-8774-bc3be46901f9/

> Just posted the URL link for latest version of Boss Tone Studio - because Roland/Boss have removed access to the download , effectively 24 hours ago (April 26, 2017) - as they state:
All downloads for ALL versions of Boss Tone Studio for Windows temporarily halted
>
> Currently it is not capable to install the application for Windows to some PC environments.
> We are stopping to provide it.
> Thank you for your kind cooperation and understanding in advance.
> https://www.boss.info/global/support/by_product/katana-head/updates_drivers/0143296a-ed7b-4530-8774-bc3be46901f9/

"We are stopping to provide it." I assume that is japanese/english for we'll drop support for this version and release a fixed version soon. Keeping a copy as well to see what happens. If it becomes a thing I can share that in the repository as a legacy thing.

**Comment by Beanow** [comment]
Moved to separate issue from #5

**Comment by Beanow** [comment]
Reading some of the comments, it does look like a big deal.
For archiving sake there is now a mirror here.

https://github.com/katana-dev/docs/raw/master/resources/LEGACY_bts_katana_w102.zip

**Comment by Beanow** [comment]
Looks like we have the download back.

> BOSS TONE STUDIO for KATANA for Windows is again available for download (May 26, 2017).

https://www.boss.info/global/support/by_product/katana-100/updates_drivers/67106378-ef76-4716-a242-863e6c84d4f3/

**Comment by Beanow** [comment]
The filesize and checksum seem to have changed in spite of not having a different version number. I will assume they repackaged some thing or another and remove the legacy copy.

**Comment by skconrad** [comment]
[The filesize and checksum seem to have changed in spite of not having a different version number. I will assume they repackaged some thing or another and remove the legacy copy.](url)

They updated the SSL Cert for the Installer 

uninstall any older BTS versions first
