### ISSUE TITLE
Slack Community

### ISSUE THREAD

**Issue by jondaiello** [katana-dev/docs#7]
I created a slack community for folks who are using the Boss Katana series of amps. I added a `katana-dev` channel for those who would like to be kept up to date.

https://bosskatanaunofficial.slack.com/

**Comment by jondaiello** [comment]
Anyone can request an invite at https://bosskatanaunofficial.slack.com/shared_invite/MTg0MzIyNDgxMjg1LTE0OTQ5NTI5MDgtNTdjNDlkNDMyMg

**Comment by Beanow** [comment]
Hi @jondaiello thanks for the invite.
Personally not much of a slack fan but let me add it to the list.
I'm assuming it's not programming specific so I would certainly suggest mentioning the community on http://www.vguitarforums.com/smf/index.php?board=231.0 as well.
